import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState, useEffect } from "react";
import axios from "axios";
import { Fruit } from "@/fruitStorage.domain/core/entities/fruit";
import FruitList from "@/components/FruitList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [fruits, setFruits] = useState<Fruit[]>([]);

  useEffect(() => {
    async function fetchFruits() {
      try {
        const response = await axios.get("/api/fruits");
        setFruits(response.data);
      } catch (error) {
        console.error("Error fetching fruits:", error);
      }
    }

    fetchFruits();
  }, []);

  return (
    <>
      <Head>
        <title>Playground - Fruit Storage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Made by Shawn -&nbsp;
            <code className={styles.code}>Next.js + TypeScript</code>
          </p>
          <div>
            <h1>Fruit Storage System 🍎</h1>
          </div>
        </div>

        <div className={styles.center}>
          <FruitList />
        </div>

        <div className={styles.grid}>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2 className={inter.className}>
              Store <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Store a specified amount of fruit to the storage.
            </p>
          </a>

          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2 className={inter.className}>
              Remove <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Remove a specified amount of fruit from the storage.
            </p>
          </a>

          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2 className={inter.className}>
              CreateFruit <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Create a new fruit in the storage.
            </p>
          </a>

          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2 className={inter.className}>
              UpdateFruit <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Update an existing fruit's properties.
            </p>
          </a>

          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2 className={inter.className}>
              DeleteFruit <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Delete a fruit from the storage;</p>
          </a>
        </div>
      </main>
    </>
  );
}
